# Generated by Django 5.2.1 on 2025-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0002_emaillog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
