# Generated by Django 5.2.1 on 2025-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0004_audience_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='tag',
            field=models.CharField(default='general_audience', max_length=30, null=True),
        ),
    ]
