# Generated by Django 5.2.1 on 2025-07-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0010_alter_campaign_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
