# Generated by Django 5.2.1 on 2025-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0011_alter_campaign_body_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sent', 'sent')], default='draft', max_length=20),
        ),
    ]
