# Generated by Django 5.2.1 on 2025-07-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0012_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='checks',
            field=models.BooleanField(default=False),
        ),
    ]
