# Generated by Django 5.2.1 on 2025-07-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0014_subscriber_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='body_html',
            new_name='html_content',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='user',
        ),
    ]
