# Generated by Django 5.2.1 on 2025-07-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0015_rename_body_html_emailtemplate_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
