# Generated by Django 5.2.1 on 2025-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0003_audience_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='tag',
            field=models.CharField(default='general_audience', max_length=30),
        ),
    ]
