# Generated by Django 5.2.1 on 2025-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0007_alter_subscriber_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
